/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sidh_SidhNative */

#ifndef _Included_sidh_SidhNative
#define _Included_sidh_SidhNative
#ifdef __cplusplus
extern "C" {
#endif
#undef sidh_SidhNative_P434
#define sidh_SidhNative_P434 1L
#undef sidh_SidhNative_P434Comp
#define sidh_SidhNative_P434Comp 2L
#undef sidh_SidhNative_P503
#define sidh_SidhNative_P503 3L
#undef sidh_SidhNative_P503Comp
#define sidh_SidhNative_P503Comp 4L
#undef sidh_SidhNative_P610
#define sidh_SidhNative_P610 5L
#undef sidh_SidhNative_P610Comp
#define sidh_SidhNative_P610Comp 6L
#undef sidh_SidhNative_P751
#define sidh_SidhNative_P751 7L
#undef sidh_SidhNative_P751Comp
#define sidh_SidhNative_P751Comp 8L
/*
 * Class:     sidh_SidhNative
 * Method:    enableLoggingCallback
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sidh_SidhNative_enableLoggingCallback
  (JNIEnv *, jobject);

/*
 * Class:     sidh_SidhNative
 * Method:    disableLoggingCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sidh_SidhNative_disableLoggingCallback
  (JNIEnv *, jclass);

/*
 * Class:     sidh_SidhNative
 * Method:    getFieldLengths
 * Signature: (I)Lsidh/SidhNative/FieldLengths;
 */
JNIEXPORT jobject JNICALL Java_sidh_SidhNative_getFieldLengths
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
