/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sidhjava_SidhNative_FieldLengths */

#ifndef _Included_sidhjava_SidhNative_FieldLengths
#define _Included_sidhjava_SidhNative_FieldLengths
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
