/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sidh_tests_SidhNativeTests */

#ifndef _Included_sidh_tests_SidhNativeTests
#define _Included_sidh_tests_SidhNativeTests
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sidh_tests_SidhNativeTests
 * Method:    runSidhTests
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sidh_tests_SidhNativeTests_runSidhTests
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
