/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sidhjava_SidhNative */

#ifndef _Included_sidhjava_SidhNative
#define _Included_sidhjava_SidhNative
#ifdef __cplusplus
extern "C" {
#endif
#undef sidhjava_SidhNative_P434
#define sidhjava_SidhNative_P434 1L
#undef sidhjava_SidhNative_P434Comp
#define sidhjava_SidhNative_P434Comp 2L
#undef sidhjava_SidhNative_P503
#define sidhjava_SidhNative_P503 3L
#undef sidhjava_SidhNative_P503Comp
#define sidhjava_SidhNative_P503Comp 4L
#undef sidhjava_SidhNative_P610
#define sidhjava_SidhNative_P610 5L
#undef sidhjava_SidhNative_P610Comp
#define sidhjava_SidhNative_P610Comp 6L
#undef sidhjava_SidhNative_P751
#define sidhjava_SidhNative_P751 7L
#undef sidhjava_SidhNative_P751Comp
#define sidhjava_SidhNative_P751Comp 8L
/*
 * Class:     sidhjava_SidhNative
 * Method:    enableLoggingCallback
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sidhjava_SidhNative_enableLoggingCallback
  (JNIEnv *, jobject);

/*
 * Class:     sidhjava_SidhNative
 * Method:    disableLoggingCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sidhjava_SidhNative_disableLoggingCallback
  (JNIEnv *, jclass);

/*
 * Class:     sidhjava_SidhNative
 * Method:    getFieldLengths
 * Signature: (I)Lsidhjava/SidhNative/FieldLengths;
 */
JNIEXPORT jobject JNICALL Java_sidhjava_SidhNative_getFieldLengths
  (JNIEnv *, jclass, jint);

/*
 * Class:     sidhjava_SidhNative
 * Method:    randomModOrderA
 * Signature: (I[B)Z
 */
JNIEXPORT jboolean JNICALL Java_sidhjava_SidhNative_randomModOrderA
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     sidhjava_SidhNative
 * Method:    randomModOrderB
 * Signature: (I[B)Z
 */
JNIEXPORT jboolean JNICALL Java_sidhjava_SidhNative_randomModOrderB
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     sidhjava_SidhNative
 * Method:    ephemeralKeyGenerationA
 * Signature: (I[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_sidhjava_SidhNative_ephemeralKeyGenerationA
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray);

/*
 * Class:     sidhjava_SidhNative
 * Method:    ephemeralKeyGenerationB
 * Signature: (I[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_sidhjava_SidhNative_ephemeralKeyGenerationB
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray);

/*
 * Class:     sidhjava_SidhNative
 * Method:    ephemeralSecretAgreementA
 * Signature: (I[B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_sidhjava_SidhNative_ephemeralSecretAgreementA
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     sidhjava_SidhNative
 * Method:    ephemeralSecretAgreementB
 * Signature: (I[B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_sidhjava_SidhNative_ephemeralSecretAgreementB
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
