/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sidhjava_test_SidhNativeTests */

#ifndef _Included_sidhjava_test_SidhNativeTests
#define _Included_sidhjava_test_SidhNativeTests
#ifdef __cplusplus
extern "C" {
#endif
#undef sidhjava_test_SidhNativeTests_TestsOnly
#define sidhjava_test_SidhNativeTests_TestsOnly 1L
#undef sidhjava_test_SidhNativeTests_TestBenchmarks
#define sidhjava_test_SidhNativeTests_TestBenchmarks 2L
#undef sidhjava_test_SidhNativeTests_EcisogFunctions
#define sidhjava_test_SidhNativeTests_EcisogFunctions 4L
#undef sidhjava_test_SidhNativeTests_DiffieHellman
#define sidhjava_test_SidhNativeTests_DiffieHellman 8L
/*
 * Class:     sidhjava_test_SidhNativeTests
 * Method:    runSidhTests
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_sidhjava_test_SidhNativeTests_runSidhTests
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
