/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sidh_tests_SidhNativeTests */

#ifndef _Included_sidh_tests_SidhNativeTests
#define _Included_sidh_tests_SidhNativeTests
#ifdef __cplusplus
extern "C" {
#endif
#undef sidh_tests_SidhNativeTests_TestsOnly
#define sidh_tests_SidhNativeTests_TestsOnly 1L
#undef sidh_tests_SidhNativeTests_TestBenchmarks
#define sidh_tests_SidhNativeTests_TestBenchmarks 2L
#undef sidh_tests_SidhNativeTests_EcisogFunctions
#define sidh_tests_SidhNativeTests_EcisogFunctions 4L
/*
 * Class:     sidh_tests_SidhNativeTests
 * Method:    runSidhTests
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_sidh_tests_SidhNativeTests_runSidhTests
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
